from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class StepOutput:
    text: str
    token_ids: list[int]
    finish_reason: str
    prompt_tokens: int = 0
    wall_time: float = 0.0
    extra: dict[str, Any] = field(default_factory=dict)

    @property
    def token_count(self) -> int:
        return len(self.token_ids)


@dataclass
class StepRecord:
    problem_id: str
    step_id: int
    generator: str      # "slm" | "llm"
    text: str
    token_ids: list[int]

    c_raw: float | None = None      # raw continuation confidence from SLM logits
    c_smooth: float | None = None   # smoothed confidence (confidence.smooth_window moving avg)

    driver_state: str | None = None  # SLM_ACTIVE | LLM_ACTIVE (state after this step)
    action: str = "TRUST"

    finish_reason: str | None = None
    prompt_tokens: int = 0
    wall_time: float = 0.0
    attempt_id: int | None = None

    active: bool = True
    is_recovery: bool = False        # kept for backward compatibility
    removed_by_rollback: bool = False  # always False in new system

    transition_type: str | None = None
    delta_c_smooth: float | None = None  # c_smooth difference from previous step

    extra: dict[str, Any] = field(default_factory=dict)

    @property
    def token_count(self) -> int:
        return len(self.token_ids)


@dataclass
class RollbackEvent:
    """Kept for backward compatibility with analysis scripts; not generated by the new algorithm."""

    problem_id: str
    type: str
    reason: str
    trigger_step: int
    anchor_step: int
    rollback_span: int
    removed_steps: list[dict]
    recovery_steps: list[dict]
    stop_reason: str
    recovery_max_steps: int
    recovery_actual_steps: int
    recovery_c_norm: list[float]
